name: slash commands

on: issue_comment

jobs:
  slach-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: release
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin

      # Create tag draft
      - name: Create tag draft
        uses: release-drafter/release-drafter@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.command.outputs.command-name

      # Generate document
      - uses: actions/checkout@v1
        if: steps.command.outputs.command-name
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ env.NIM_VERSION }}
        if: steps.command.outputs.command-name
      - uses: jiro4989/setup-nim-action@v1.0.1
        if: steps.command.outputs.command-name
      - name: Generate documents
        run: nimble docs
        if: steps.command.outputs.command-name
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
        if: steps.command.outputs.command-name

      - run: echo "end"
